<a href="https://colab.research.google.com/github/YAshRaj412/Assignment/blob/main/NumPy_Practice_40Q.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Questions

**Instructions:** Dear Students Each question is self‑explanatory. Read the markdown prompt and write the code in the cell below it where marked `# answer here`. Keep solutions simple and focused on the asked concept.

- Q1–Q30: Single-topic questions in sequence (basics → indexing → operations → aggregations → reshaping/broadcasting → utilities).

- Q31–Q35: Multi‑concept (combine 2–3 ideas you practiced).

- Q36–Q40: Use a single dataset loaded via **pandas** and perform **NumPy** operations on it. The file `students_scores.csv` is already available in the same folder as this notebook.


### Q1. Create a 1D NumPy array from the Python list `[1, 2, 3, 4, 5]` and print its type and contents.

In [ ]:
# answer here
import numpy as np
arr = np.array([1,2,3,4,5])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


### Q2. Create a 2D NumPy array from `[[1, 2, 3], [4, 5, 6]]` and print its `shape` and `ndim`.

In [ ]:
# answer here
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)

(2, 3)
2


### Q3. Create an array of 6 zeros and print it.

In [ ]:
# answer here
arr = np.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


### Q4. Create an array of 5 ones (float) and print it.

In [ ]:
# answer here
arr = np.ones(5,dtype=float)
print(arr)

[1. 1. 1. 1. 1.]


### Q5. Use `np.arange` to create an array from 2 to 14 (inclusive of 2, exclusive of 14) with a step of 2 and print it.

In [ ]:
# answer here
arr = np.arange(2,14,2)
print(arr)

[ 2  4  6  8 10 12]


### Q6. Use `np.linspace` to create 5 evenly spaced values from 0 to 1 and print them.

In [ ]:
# answer here
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


### Q7. Create an integer array `[10, 20, 30]` then convert it to `float` dtype and print both arrays.

In [ ]:
# answer here
arr = np.array([10,20,30])
arr = arr.astype(float)
print(arr)

[10. 20. 30.]


### Q8. Create an array of 12 numbers from 0 to 11 and reshape it to `3x4`; print the reshaped array.

In [ ]:
# answer here
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Q9. For the array `a = np.array([[1,2,3],[4,5,6]])`, print `a.shape`, `a.ndim`, and `a.size`.

In [ ]:
# answer here
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.size)

(2, 3)
2
6


### Q10. For the array `a = np.array([1,2,3], dtype=np.int32)`, print `a.dtype` and `a.itemsize`.

In [ ]:
# answer here
a = np.array([1,2,3], dtype=np.int32)
print(a.dtype)
print(a.itemsize)

int32
4


### Q11. Given `arr = np.array([10, 20, 30, 40, 50])`, print the first element, last element, and the element at index 2.

In [ ]:
# answer here
arr = np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[2])

10
50
30


### Q12. Given `arr = np.array([5, 10, 15, 20, 25])`, use negative indexing to print the last two elements.

In [ ]:
# answer here
arr = np.array([5,10,15,20,25])
print(arr[-2:])

[20 25]


### Q13. Given `arr = np.array([0,1,2,3,4,5,6,7,8,9])`, print the slice from index 2 to 7 (exclusive).

In [ ]:
# answer here
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[2:7])

[2 3 4 5 6]


### Q14. Given `m = np.arange(1,13).reshape(3,4)`, print the second row and the third column (as 1D slices).

In [ ]:
# answer here
m = np.arange(1,13).reshape(3,4)
print(m[1])
print(m[:,2])

[5 6 7 8]
[ 3  7 11]


### Q15. Given `m = np.arange(1,13).reshape(3,4)`, print the submatrix containing rows 0 to 1 and columns 1 to 3.

In [ ]:
# answer here
m = np.arange(1,13).reshape(3,4)
print(m[:2,1:3])

[[2 3]
 [6 7]]


### Q16. Given `arr = np.arange(1,11)`, create a boolean mask for even numbers and print the even elements.

In [ ]:
# answer here
arr = np.arange(1,11)
mask = arr%2==0
print(arr[mask])

[ 2  4  6  8 10]


### Q17. Given `arr = np.arange(1,11)`, set all odd elements to `-1` (modify in place) and print the result.

In [ ]:
# answer here
arr = np.arange(1,11)
arr[arr%2!=0] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


### Q18. Given `arr = np.array([1,2,3])`, add `5` to every element and print the result (element‑wise).

In [ ]:
# answer here
arr = np.array([1,2,3])
print(arr+5)

[6 7 8]


### Q19. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, print `a + b` and `a * b` (element‑wise).

In [ ]:
# answer here
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)

[5 7 9]
[ 4 10 18]


### Q20. Given `a = np.array([1,2,3])` and `b = np.array([[10],[20],[30]])`, use broadcasting to compute `a + b` and print it.

In [ ]:
# answer here
a = np.array([1,2,3])
b = np.array([[10],[20],[30]])
print(a+b)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Q21. Given `arr = np.array([3, 7, 2, 9, 5])`, print its `sum`, `mean`, `min`, and `max`.

In [ ]:
# answer here
arr = np.array([3,7,2,9,5])
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())

26
5.2
2
9


### Q22. Given `m = np.arange(1,13).reshape(3,4)`, print the sum along axis 0 and along axis 1.

In [ ]:
# answer here
m = np.arange(1,13).reshape(3,4)
print(m.sum(axis=0))
print(m.sum(axis=1))

[15 18 21 24]
[10 26 42]


### Q23. Given `arr = np.array([10, 20, 5, 40, 25])`, print the indices of the `max` and `min` elements using `np.argmax` and `np.argmin`.

In [ ]:
# answer here
arr = np.array([10,20,5,40,25])
print(np.argmax(arr))
print(np.argmin(arr))

3
2


### Q24. Given `arr = np.array([3, 3, 1, 2, 2, 2, 5])`, print the sorted array and the unique values using `np.unique`.

In [ ]:
# answer here
arr = np.array([3,3,1,2,2,2,5])
print(np.sort(arr))
print(np.unique(arr))

[1 2 2 2 3 3 5]
[1 2 3 5]


### Q25. Given `arr = np.array([9, 1, 5, 3, 7])`, sort it in ascending order and print the result (do not modify original).

In [ ]:
# answer here
arr = np.array([9,1,5,3,7])
print(np.sort(arr))

[1 3 5 7 9]


### Q26. Given `a = np.array([1,2,3])` and `b = np.array([4,5,6])`, horizontally concatenate them and print the result.

In [ ]:
# answer here
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.hstack((a,b)))

[1 2 3 4 5 6]


### Q27. Given `A = np.array([[1,2],[3,4]])` and `B = np.array([[5,6],[7,8]])`, stack them vertically and print the result.

In [ ]:
# answer here
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.vstack((A,B)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Q28. Given `arr = np.arange(1,13)`, split it into 3 equal parts and print each part.

In [ ]:
# answer here
arr = np.arange(1,13)
print(np.split(arr,3))

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


### Q29. Set a random seed (e.g., 42), generate 5 random integers from 0 to 9 using `np.random.randint`, and print them.

In [ ]:
# answer here
np.random.seed(42)
print(np.random.randint(0,9,5))

[6 3 7 4 6]


### Q30. Given `arr = np.array([-3, 1, -1, 4, -2, 5])`, use `np.where` to replace negative values with `0` and print the new array.

In [ ]:
# answer here
arr = np.array([-3,1,-1,4,-2,5])
print(np.where(arr<0,0,arr))

[0 1 0 4 0 5]


### Q31. Create a 3D array of shape `(2, 3, 4)` using `np.arange` then compute the mean along axis 2 and print the result.

In [ ]:
# answer here
arr = np.arange(24).reshape(2,3,4)
print(np.mean(arr,axis=2))

[[ 1.5  5.5  9.5]
 [13.5 17.5 21.5]]


### Q32. Create an array from `[5, 10, 15, 20, 25]`, slice out `[10, 15, 20]`, then normalize that slice to range 0–1 using min‑max formula and print it.

In [ ]:
# answer here
arr = np.array([5,10,15,20,25])
print((arr[1:4]-arr[1:4].min())/(arr[1:4].max()-arr[1:4].min()))

[0.  0.5 1. ]


### Q33. Create two 1D arrays `a=[1,2,3]` and `b=[4,5,6]`; compute the dot product and also form a `3x2` matrix from `a` and `b` and print both results.

In [ ]:
# answer here
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b))
print(np.outer(a,b))

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


### Q34. Create an array of 12 values (1–12), reshape it to `3x4`, then count how many values are greater than `6` and print the count.

In [ ]:
# answer here
arr = np.arange(1,13).reshape(3,4)
print(np.count_nonzero(arr>6))

6


### Q35. Create an array from 0–9; replace all odd numbers with `-1` *except* keep the first and last elements unchanged; print the final array.

In [ ]:
# answer here
arr = np.arange(10)
arr[1:-1][arr[1:-1]%2!=0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8  9]


### Dataset for Q36–Q40

A CSV file **`students_scores.csv`** is already placed in this folder (Link-https://drive.google.com/file/d/1B7zDahhmQzXkQmvskS27H07B4Xftf9xA/view?usp=sharing).  

Columns: `id, math, english, science` (10 students). Use **pandas** to import the file and then perform **NumPy** operations.


### Q36. Import `students_scores.csv` as a pandas DataFrame `df`. Then convert the `math`, `english`, and `science` columns to separate NumPy arrays and print their shapes.

In [ ]:
# answer here
import pandas as pd
df = pd.read_csv("students_scores.csv")
math = df["math"].values
english = df["english"].values
science = df["science"].values
print(math.shape)

(10,)


### Q37. Using NumPy on the arrays from Q36, compute the mean score of each subject (math, english, science) and print them.

In [ ]:
# answer here
print(math.mean())
print(english.mean())
print(science.mean())

70.3
69.5
70.1


### Q38. Using NumPy, compute each student’s **total score** (math + english + science) and print the `id` of the student with the highest total.

In [ ]:
# answer here
total = math+english+science
print(df.iloc[total.argmax()]["id"])

S03


### Q39. Using NumPy, standardize the `math` scores to **z-scores**: `(x - mean) / std` and print the first 5 standardized values.

In [ ]:
# answer here
print((math-math.mean())/math.std())


[ 0.53032869 -0.98489614  1.21906724 -1.74250855  1.49456267 -0.22728372
  0.18595941 -0.77827457  0.94357182 -0.64052686]


In [ ]:
# this is how you can approach question number 39
# dont fear about std(standard deviation , just google it and you understand its simple, else you can connect for doubts)


import pandas as pd
import numpy as np

# Load the dataset
df = pd.read_csv("students_scores.csv")

# Extract math column as NumPy array
math_scores = df["math"].values

# Compute z-scores
z_scores = (math_scores - np.mean(math_scores)) / np.std(math_scores)

# Print first 5 standardized values
print(z_scores[:5])


[ 0.53032869 -0.98489614  1.21906724 -1.74250855  1.49456267]


### Q40. Using NumPy logical operations, count how many students scored **≥ 70 in all three subjects** and print that count.

In [ ]:
# answer here
print(np.count_nonzero((math>=70) & (english>=70) & (science>=70)))


3
